language: python

python:
  - "2.7"

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - libyajl-dev
    - libxml2-dev
    - gcc-4.9
    - g++-4.9
    - clang
    - libboost-python1.55-dev
    - python-scipy
    - liblapack-dev
    - libfftw3-dev

before_install:
#  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#  - sudo add-apt-repository ppa:boost-latest/ppa -y
#  - sudo apt-add-repository ppa:cython-dev/master-ppa -y
#  - sudo apt-get -qq update
#  - sudo apt-get install -qq gcc-4.9
#  - sudo apt-get install -qq g++-4.9
  - export CC=gcc-4.9
  - export CXX=g++-4.9
#  - sudo apt-get install -qq libboost-python1.55-dev
#  - sudo apt-get install libfftw3-dev
#  - sudo apt-get build-dep python-numpy python-scipy
  - pip install --upgrade pip
  - pip install scipy
  - pip install pyfftw
  - pip install nose

install: 
  - pip install .

script: nosetests
 
notifications:
  email: false

