language: python

python:
  - "2.7"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-add-repository ppa:cython-dev/master-ppa -y
  - sudo apt-get -qq update
  - sudo apt-get install -qq libboost-python1.55-dev
  - sudo apt-get install -qq gcc-4.9
  - sudo apt-get install -qq g++-4.9
  - export CC=/usr/bin/gcc-4.9
  - export CXX=/usr/bin/g++-4.9
  - pip install --upgrade pip
  - pip install scipy
  - pip install nose

install: 
  - pip install .

script: nosetests
 
notifications:
  email: false

