language: python

python:
  - "2.7"

sudo: false

git:
  submodules: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - libyajl-dev
    - libxml2-dev
    - gcc-4.9
    - g++-4.9
    - clang
    - libboost-python1.55-dev
    - python-scipy
    - liblapack-dev
    - libfftw3-dev
    - gfortran

before_install:
  - export CC=gcc-4.9
  - export CXX=g++-4.9
  - pip install --upgrade pip
  - pip install scipy
  - pip install pyfftw
  - pip install nose

install: 
  - pip install .

script: nosetests -v
 
notifications:
  email: false

